kube-ovn:
  #namespace: kube-system
  ipv4:
    POD_CIDR: "10.45.0.0/16"
    POD_GATEWAY: "10.45.0.1"
    SVC_CIDR: "172.45.0.0/16"
    JOIN_CIDR: "100.64.0.0/16"
  MASTER_NODES_LABEL: "node-role.kubernetes.io/control-plane"
  cni_conf:
    CNI_CONFIG_PRIORITY: "10"
    MOUNT_LOCAL_BIN_DIR: false
  OPENVSWITCH_DIR: "/etc/origin/openvswitch"
  OVN_DIR: "/etc/origin/ovn"
  DISABLE_MODULES_MANAGEMENT: false