kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: 0.30.6@sha256:c003b9d2503ff126f2f9ec01629fe4012c765a6cd548796656137e56c071f98c
    repository: ccpr.cocktailcloud.io/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
